# ================================
# ================================
#  Personal Finance Tracker Config
# ================================
spring.datasource.url=jdbc:mysql://localhost:3306/finance_tracker
spring.datasource.username=root
spring.datasource.password=Ranees@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ✅ Fix: serialize LocalDate as "2025-03-01" string not [2025,3,1] array
spring.jackson.serialization.write-dates-as-timestamps=false

spring.application.name=finance-tracker
server.port=8080